# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  # desc "Submit a new Beta Build to Crashlytics Beta"
  # lane :beta do
  #   gradle(task: "clean assembleRelease")
  #   crashlytics
  
  #   # sh "your_script.sh"
  #   # You can also use other beta testing services here
  # end

  desc "Deploy a new version to the Google Play"
  lane :alpha do
    build_number = number_of_commits(all: true)
    Dir.chdir "../.." do
      sh("flutter", "packages", "get")
      sh("flutter", "clean")
      sh("flutter", "build", "appbundle", "--build-number=#{build_number}")
    end
    upload_to_play_store(
      track: "alpha",
      skip_upload_changelogs: true,
      aab: "../build/app/outputs/bundle/release/app-release.aab"
      )
  end

  desc "Deploy a new version to the Google Play"
  lane :beta do
    build_number = number_of_commits(all: true)
    Dir.chdir "../.." do
      sh("flutter", "packages", "get")
      sh("flutter", "clean")
      sh("flutter", "build", "appbundle", "--build-number=#{build_number}")
    end
    upload_to_play_store(
      track: "beta",
      skip_upload_changelogs: true,
      aab: "../build/app/outputs/bundle/release/app-release.aab"
      )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    build_number = number_of_commits(all: true)
    Dir.chdir "../.." do
      sh("flutter", "packages", "get")
      sh("flutter", "clean")
      sh("flutter", "build", "appbundle", "--build-number=#{build_number}")
    end
    upload_to_play_store(
      skip_upload_changelogs: true,
      aab: "../build/app/outputs/bundle/release/app-release.aab"
      )
  end
end
